### ISSUE TITLE
Exception in the call to LeapPollConnection function

### ISSUE THREAD

**Issue by EpoUnlimited** [hsreina/Leap-Motion-Delphi-SDK-Samples#1]
Tested with Tokyo R3  and install 4.0
Proejct LepaMotionDemo.exe raised exception class $C00008E with message 'c000008e FLOAT_DIVIDE_BY ZERO.
Remarks: It is in a VM but the visualize and the visualizer diagnostic runs without problem.

**Comment by hsreina** [comment]
Is your firmware of the Leap Motion 1.7.0?
What OS version did you used?
Built the 32bit app?
If you can give me more information.

**Comment by EpoUnlimited** [comment]
Firmware is 1.7.0
Win10 Pro and app built in 64bits (The DLL is 64 bits)
Thanks a lot,

**Comment by hsreina** [comment]
I fixed it in #2 
https://github.com/hsreina/Leap-Motion-Delphi-SDK-Samples/blob/master/src/LeapMotionDemo.dpr#L22
I ve added 
`SetMXCSR(GetMXCSR() or (1 shl 7) or (1 shl 9));`
just before the application.Initialize.
I don't know why, Delphi change MXCSR default values on the Initialization of the application.
I didn't made the fix inside the headers code because I think that the application should decide about that.
